# Sentinel — self-extracting installer (TEMPLATE).
# Generated by build-installer.ps1 with @@BUNDLE_B64@@ replaced by the
# base64-encoded source-zip at build time.

$ErrorActionPreference = "Stop"

# Wrap EVERYTHING so a fatal error doesn't close the window before
# the user can read it. Final Read-Host keeps the terminal up so they
# can copy any error.
function Invoke-Installer {

# ============================ BANNER ============================
try { Clear-Host } catch {}
Write-Host @"
+============================================================+
|                                                            |
|   SENTINEL  -  self-extracting installer                   |
|                                                            |
|   This single .exe contains the Sentinel source code.      |
|   It will:                                                 |
|     1. Ask where to install                                |
|     2. Extract the source to that folder                   |
|     3. Run setup.ps1 to install Python / Ollama / models / |
|        deps / Claude CLI / Telegram credentials            |
|                                                            |
|   Total time: ~5-15 min on a fresh PC.                     |
|   Disk usage: ~3 GB (Qwen weights, downloaded by setup).   |
|                                                            |
+============================================================+

"@ -ForegroundColor Cyan

# ============================ TARGET DIR ============================
$default = Join-Path $env:USERPROFILE "sentinel"
$entered = Read-Host "Install location [$default]"
$TargetDir = if ($entered) { $entered } else { $default }

if (Test-Path $TargetDir) {
    $items = @(Get-ChildItem -Path $TargetDir -Force -ErrorAction SilentlyContinue)
    if ($items.Count -gt 0) {
        Write-Host ""
        Write-Host "  !!  $TargetDir is non-empty." -ForegroundColor Yellow
        $proceed = Read-Host "Type 'yes' to extract OVER it (existing files may be overwritten), anything else aborts"
        if ($proceed -ne "yes") {
            Write-Host "Aborted." -ForegroundColor Red
            exit 1
        }
    }
} else {
    New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
}

# ============================ DECODE + EXTRACT ============================
# Chunked array workaround for Windows PowerShell 5.1 parser limit on
# very large here-strings (~1 MB+). Each chunk is a small quoted string;
# -join '' concatenates them at runtime with no parser stress.
$BundleB64Chunks = @(
@@BUNDLE_CHUNKS@@
)
$BundleB64 = -join $BundleB64Chunks

Write-Host ""
Write-Host "Decoding embedded bundle..." -ForegroundColor Yellow
$tempZip = Join-Path $env:TEMP "sentinel-extract-$([System.Guid]::NewGuid().ToString('N')).zip"
try {
    [System.IO.File]::WriteAllBytes(
        $tempZip,
        [Convert]::FromBase64String($BundleB64.Trim())
    )
    $zipSize = (Get-Item $tempZip).Length
    Write-Host ("  OK  $([math]::Round($zipSize/1MB, 2)) MB zip on disk") -ForegroundColor Green

    Write-Host "Extracting to $TargetDir ..." -ForegroundColor Yellow
    Expand-Archive -Path $tempZip -DestinationPath $TargetDir -Force
    Write-Host "  OK  Source extracted" -ForegroundColor Green
} finally {
    if (Test-Path $tempZip) { Remove-Item $tempZip -Force -ErrorAction SilentlyContinue }
}

# ============================ SANITY CHECK ============================
$setup = Join-Path $TargetDir "setup.ps1"
if (-not (Test-Path $setup)) {
    Write-Host ""
    Write-Host "  XX  setup.ps1 missing in $TargetDir after extract." -ForegroundColor Red
    Write-Host "      Bundle may be corrupt. Try rebuilding the .exe." -ForegroundColor Red
    exit 1
}

# ============================ CHAIN ============================
Write-Host ""
Write-Host "Chaining into setup.ps1 ..." -ForegroundColor Cyan
Write-Host ""
Set-Location $TargetDir
& $setup
return $LASTEXITCODE
}

# Run + always pause on completion / error so the window doesn't vanish.
$exitCode = 0
try {
    $exitCode = Invoke-Installer
} catch {
    Write-Host ""
    Write-Host "==========================================================" -ForegroundColor Red
    Write-Host "  INSTALLER ERROR" -ForegroundColor Red
    Write-Host "==========================================================" -ForegroundColor Red
    Write-Host ""
    Write-Host ("Exception: " + $_.Exception.GetType().FullName) -ForegroundColor Red
    Write-Host ("Message:   " + $_.Exception.Message) -ForegroundColor Red
    Write-Host ""
    Write-Host "Stack trace:" -ForegroundColor DarkGray
    Write-Host $_.ScriptStackTrace -ForegroundColor DarkGray
    Write-Host ""
    $exitCode = 1
}
Write-Host ""
Read-Host "Press Enter to close this window"
exit $exitCode
