"""Phase 13 (Batch 5b): query expansion for /jobsearch.

A single /jobsearch query is broadened into up to N variants before it
hits jobspy. Each variant runs a separate scrape; rows are deduped by
URL in job_scrape before the title filter. Triples coverage on jargon
("RSM" doesn't surface postings titled "Regional Sales Manager" without
expansion).

Deterministic only -- no LLM call. The map is hand-curated for the
sales archetypes in PROFILE; new jargon -> add a row here. Brain-based
expansion was considered but skipped: the GPU swap (qwen3-brain ↔
qwen2.5:3b for extract/score) costs ~5s and gains little over a static
abbreviation map for known sales titles.
"""
from __future__ import annotations

from core import config
from core.logger import log_event


# Lowercase abbreviation -> list of expansions. Each substring match
# in the user's query line yields one variant per expansion.
# Bidirectional: 'rsm' -> 'regional sales manager' AND vice-versa.
ABBREV_MAP: dict[str, list[str]] = {
    "rsm": ["regional sales manager", "regional manager"],
    "regional sales manager": ["rsm", "area sales manager"],
    "tsm": ["territory sales manager", "territory manager"],
    "territory sales manager": ["tsm", "field sales manager"],
    "ae": ["account executive"],
    "account executive": ["ae", "named account manager",
                          "enterprise account executive"],
    "sdr": ["sales development representative"],
    "bdr": ["business development representative"],
    "csm": ["customer success manager"],
    "customer success manager": ["csm", "client success manager"],
    "revops": ["sales operations", "revenue operations", "rev ops"],
    "sales operations": ["revops", "revenue operations", "sales ops"],
    "revenue operations": ["revops", "sales operations"],
    "sales ops": ["sales operations", "revops"],
    "vp sales": ["vice president sales", "vp of sales"],
    "vice president sales": ["vp sales", "vp of sales"],
    "director sales": ["sales director", "director of sales"],
    "sales director": ["director of sales", "director sales"],
}


def expand_query(query: str, max_variants: int | None = None) -> list[str]:
    """Return [original, *variants] -- a deduped, ordered list of search
    queries to run. Always includes the original first. Variants are
    generated by substring-matching ABBREV_MAP keys (case-insensitive)
    and substituting the expansions one at a time.

    Capped at ``max_variants`` (default ``config.JOB_QUERY_EXPANSION_MAX``).
    Returns ``[query]`` unchanged when expansion is disabled or no map
    entries match.
    """
    q = (query or "").strip()
    if not q:
        return []
    cap = max_variants or getattr(config, "JOB_QUERY_EXPANSION_MAX", 3)
    if not getattr(config, "JOB_QUERY_EXPANSION_ENABLED", True):
        return [q]
    if cap <= 1:
        return [q]

    out: list[str] = [q]
    seen_lower = {q.lower()}
    q_lower = q.lower()
    # Find every abbrev key that appears as a substring. For each match,
    # generate variants by substituting once per expansion. Order is
    # stable (longest keys first so multi-word expansions take priority
    # over single-word collisions).
    for key in sorted(ABBREV_MAP.keys(), key=len, reverse=True):
        if key not in q_lower:
            continue
        for replacement in ABBREV_MAP[key]:
            if len(out) >= cap:
                break
            # Case-insensitive substitute. Preserves the rest of the
            # query verbatim so "RSM Detroit" -> "Regional Sales Manager
            # Detroit", not "regional sales manager detroit".
            idx = q_lower.find(key)
            new_q = q[:idx] + replacement + q[idx + len(key):]
            new_lower = new_q.lower()
            if new_lower not in seen_lower:
                seen_lower.add(new_lower)
                out.append(new_q)
        if len(out) >= cap:
            break

    return out[:cap]


def log_expansion(query: str, variants: list[str], trace_id: str) -> None:
    """Helper for callers to log the expansion uniformly."""
    if len(variants) <= 1:
        return
    log_event(
        trace_id, "INFO", "query_expansion",
        f"expanded {query!r} -> {len(variants)} variants: {variants}",
    )
